baseURL = 'https://mariol03.es/'
languageCode = 'es'
theme = 'beautifulhugo-master'
title = 'Porfolio'

[params.author]
name = 'Mario Laglera'

[[menu.main]]
    name = 'Markdown'
    url = '/markdown'
    weight = 1

[[menu.main]]
    name = 'Hobbies'
    url = '/hobbies'
    weight = 1

[[menu.main]]
    name = 'Proyectos'
    weight = 1

[[menu.main]]
    parent = 'Proyectos'
    name = 'GeoLogMapper'
    url = '/proyectos/GeoLogMapper'
    weight = 2

[[menu.main]]
    parent = 'Proyectos'
    name = 'AutoTranscription'
    url = '/proyectos/AutoTranscription'
    weight = 3