baseURL = 'https://mariol03.es/'
languageCode = 'es'
theme = 'beautifulhugo'
title = 'Porfolio'

[params.author]
name = 'Mario Laglera'

[[menu.main]]
    name = 'Markdown'
    url = '/markdown'
    weight = 1

[[menu.main]]
    name = 'Hobbies'
    url = '/hobbies'
    weight = 1
